#!/bin/bash

usage="usage: $(basename $0) -r chr:pos [-q base quality] [-Q mapping quality] <BAM file 1> <BAM file 2> ..."

while getopts r:q:Q: opt; do
    case $opt in
        r) OPTPOS=$OPTARG;;
        q) q=$OPTARG;;
        Q) Q=$OPTARG;;
        ?) echo $usage; exit 100
    esac
done

shift $(($OPTIND-1))

if [ -z $OPTPOS ] || [ $# -lt 1 ]; then
    echo $usage; exit 100
fi

if [ -z $q ]; then q=20; fi
if [ -z $Q ]; then Q=20; fi

CHR=${OPTPOS%%:*}
POS=${OPTPOS##*:}
START=${POS%%-*}
END=${POS##*-}
BAMS=$*;


for B in $BAMS; do
    echo $(basename $B)
    samtools mpileup -r $CHR:$START-$END -q $q -Q $Q $B \
        | cut -f 5 | fold -w 1 | grep '[AGCTagct]' | sort | uniq -c
done 2> /dev/null
